//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.huewu.cleancodeexample.clean;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import com.huewu.cleancodeexample.R.layout;

public final class CleanHeaderFragment_
    extends CleanHeaderFragment
{

    private View contentView_;

    private void init_(Bundle savedInstanceState) {
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
        {
            View view = findViewById(com.huewu.cleancodeexample.R.id.header_text);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        CleanHeaderFragment_.this.onClickText();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(com.huewu.cleancodeexample.R.id.header_image);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        CleanHeaderFragment_.this.onClickImage();
                    }

                }
                );
            }
        }
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.header, container, false);
        }
        afterSetContentView_();
        return contentView_;
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static CleanHeaderFragment_.FragmentBuilder_ builder() {
        return new CleanHeaderFragment_.FragmentBuilder_();
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public CleanHeaderFragment build() {
            CleanHeaderFragment_ fragment_ = new CleanHeaderFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
