//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.huewu.cleancodeexample.clean;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.support.v4.app.FragmentActivity;
import android.util.Log;
import android.view.KeyEvent;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import com.googlecode.androidannotations.api.BackgroundExecutor;
import com.googlecode.androidannotations.api.SdkVersionHelper;
import com.huewu.cleancodeexample.ContentFragment;
import com.huewu.cleancodeexample.HeaderFragment;
import com.huewu.cleancodeexample.R.layout;

public final class CleanMainActivity_
    extends CleanMainActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.activity_main);
    }

    private void init_(Bundle savedInstanceState) {
    }

    private void afterSetContentView_() {
        mContentFrag = ((ContentFragment) findSupportFragmentByTag("content"));
        mHeaderFrag = ((HeaderFragment) findSupportFragmentByTag("header"));
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static CleanMainActivity_.IntentBuilder_ intent(Context context) {
        return new CleanMainActivity_.IntentBuilder_(context);
    }

    private Fragment findSupportFragmentByTag(String tag) {
        if (!(this instanceof FragmentActivity)) {
            return null;
        }
        FragmentActivity activity_ = ((FragmentActivity) this);
        return activity_.getSupportFragmentManager().findFragmentByTag(tag);
    }

    @Override
    public void doSleep() {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    CleanMainActivity_.super.doSleep();
                } catch (RuntimeException e) {
                    Log.e("CleanMainActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, CleanMainActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public CleanMainActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
